server:
  port: 8081

spring:
  application:
    name: auth-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: azerarfa606606@gmail.com
    password: sfqiycedqioxzjux
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: "optional:configserver:http://localhost:8888"
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: auth-service
